version: '3.8'

services:
  app:
    build: .
    container_name: aiops_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./:/app  # ver cambios sin reconstruir todo en desarrollo

  qdrant:
    image: qdrant/qdrant:v1.3.5
    container_name: aiops_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  n8n:
    image: n8nio/n8n:latest
    container_name: aiops_n8n
    env_file: .env
    ports:
      - "5678:5678"
    depends_on:
      - app
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  qdrant_data:
  n8n_data:
